# Generated by Django 3.2.6 on 2021-08-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='aidata',
            name='text',
        ),
    ]
