# Generated by Django 3.2.6 on 2021-08-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20210816_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Ai Notice',
            },
        ),
        migrations.CreateModel(
            name='ComNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Computer Notice',
            },
        ),
        migrations.DeleteModel(
            name='AiData',
        ),
        migrations.DeleteModel(
            name='ComData',
        ),
    ]
