# Generated by Django 3.2.6 on 2021-08-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Ai Notice',
            },
        ),
        migrations.CreateModel(
            name='ComNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Computer Notice',
            },
        ),
    ]
