# Generated by Django 3.2.6 on 2021-08-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ainotice',
            name='specific_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comnotice',
            name='specific_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ainotice',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='comnotice',
            name='date',
            field=models.DateField(),
        ),
    ]
