# Generated by Django 3.2.6 on 2021-08-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('require', models.BooleanField()),
                ('year', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('track', models.CharField(blank=True, choices=[('language & ai', 'Language & AI'), ('software & ai', 'Software & AI'), ('business & ai', 'Business & AI'), ('common', 'Common')], max_length=20)),
            ],
        ),
    ]
